#!/usr/bin/env bash
#
# package_tournament.sh — serialize the ENTIRE tournament into one object.
#
# Assembles a monorepo that holds every piece of the tournament and emits a single,
# self-verifying `tournament.bundle` (git bundle = all history + refs in one file).
# Re-hydrate anywhere, offline, with `git clone tournament.bundle`.
#
# Layout (extensible to future tournaments — add a sibling under tournaments/):
#   tournaments/congruency-2026/
#     ├── MANIFEST.txt                inventory + provenance (source HEAD of each piece)
#     ├── brief/prompt.txt            the mission
#     ├── lineage/*.bundle            code lineage: original -> refactors -> submission (full history)
#     ├── submission/                 the evolved entry, checked out for browsing
#     ├── apparatus/*.bundle          harness / tests / bugs / coverage / pwdriver (full history each)
#     ├── database/                   deterministic seed + SQL dump (no live binaries)
#     └── docs/                       LINEAGE.md, submission_00.txt, README
#
# "Other gits" are folded in as their OWN bundles (self-contained, history preserved);
# the database as a reproducible dump; the interpreter as an INSTALL note, not a blob.
# Deterministic identity/date on the outer commit; re-runnable.
#
# Usage:  ./package_tournament.sh [DEST]        (default: ~/tournament-package)
#
set -euo pipefail

ROOT="${TOURNAMENT_ROOT:-/home/notificationsforsteven}"
ENTRY_HASH="2a2e4f8c142eafaac061fe1cebc3c93cf27849b3"
HERE="$(cd "$(dirname "$0")" && pwd)"
PHP="$ROOT/congruencey-harness/php/php"
DEST="${1:-$ROOT/tournament-package}"
T="$DEST/tournaments/congruency-2026"

git --version >/dev/null || { echo "git required"; exit 127; }

echo ">> packaging tournament into: $DEST"
rm -rf "$DEST"; mkdir -p "$T"/{brief,lineage,submission,apparatus,database,docs}

# --- provenance helper ---------------------------------------------------------------
manifest() { printf '%-26s %s  %s\n' "$1" "$2" "$3" >> "$T/MANIFEST.txt"; }
echo "TOURNAMENT PACKAGE — component inventory & provenance"      >  "$T/MANIFEST.txt"
echo "generated by package_tournament.sh (git bundle = self-contained history)" >> "$T/MANIFEST.txt"
printf '%-26s %s  %s\n' "component" "source-HEAD" "note"          >> "$T/MANIFEST.txt"
echo "-------------------------------------------------------------------------" >> "$T/MANIFEST.txt"

# --- 1. the brief --------------------------------------------------------------------
echo ">> [1/6] brief"
cp "$ROOT/prompt.txt" "$T/brief/prompt.txt"
manifest "brief/prompt.txt" "--------" "the mission"

# --- 2. code lineage (rebuilt deterministically, then bundled) -----------------------
echo ">> [2/6] code lineage (original -> refactors -> submission)"
"$HERE/assemble_lineage.sh" "$ROOT/.lineage-tmp" >/dev/null
git -C "$ROOT/.lineage-tmp" bundle create "$T/lineage/tournament-lineage.bundle" --all >/dev/null 2>&1
L_HEAD=$(git -C "$ROOT/.lineage-tmp" rev-parse --short HEAD)
rm -rf "$ROOT/.lineage-tmp"
manifest "lineage/*.bundle" "$L_HEAD" "3 stages, full history + tags"

# --- 3. the submission tree (content, for browsing) ----------------------------------
echo ">> [3/6] submission tree"
git -C "$ROOT/congruencey" archive "HEAD:$ENTRY_HASH/" | tar -x -C "$T/submission"
S_HEAD=$(git -C "$ROOT/congruencey" rev-parse --short HEAD)
manifest "submission/" "$S_HEAD" "evolved entry, checked out"

# --- 4. apparatus repos as self-contained bundles ------------------------------------
echo ">> [4/6] apparatus repos -> bundles"
for repo in congruencey-harness congruencey-tests congruencey-bugs coverage pwdriver; do
  [ -d "$ROOT/$repo/.git" ] || continue
  name="${repo#congruencey-}"
  git -C "$ROOT/$repo" bundle create "$T/apparatus/$name.bundle" --all >/dev/null 2>&1
  h=$(git -C "$ROOT/$repo" rev-parse --short HEAD)
  sz=$(du -h "$T/apparatus/$name.bundle" | cut -f1)
  manifest "apparatus/$name.bundle" "$h" "full history ($sz)"
done

# --- 5. database: deterministic seed + SQL dump (no live binaries) --------------------
echo ">> [5/6] database (seed + deterministic dump)"
cp "$ROOT/congruencey-harness/seed.php" "$T/database/seed.php"
cat > "$ROOT/.dbdump.php" <<'DUMP'
<?php
$src = $argv[1];
if (!file_exists($src)) { fwrite(STDERR, "no db\n"); exit(0); }
$db = new PDO('sqlite:'.$src); $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$tables = $db->query("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);
echo "-- deterministic dump of ".basename($src)."\nPRAGMA foreign_keys=OFF;\nBEGIN TRANSACTION;\n";
foreach ($tables as $t) {
    echo trim($t['sql']).";\n";
    $rows = $db->query("SELECT * FROM \"{$t['name']}\"")->fetchAll(PDO::FETCH_ASSOC);
    usort($rows, fn($a,$b)=>strcmp(json_encode($a),json_encode($b)));  // stable order
    foreach ($rows as $r) {
        $cols = array_map(fn($c)=>"\"$c\"", array_keys($r));
        $vals = array_map(fn($v)=>$v===null?'NULL':$db->quote((string)$v), array_values($r));
        echo "INSERT INTO \"{$t['name']}\" (".implode(',',$cols).") VALUES (".implode(',',$vals).");\n";
    }
}
echo "COMMIT;\n";
DUMP
if [ -x "$PHP" ]; then
  "$PHP" "$ROOT/.dbdump.php" "$ROOT/congruencey-harness/congruency.sqlite" > "$T/database/congruency.dump.sql" 2>/dev/null || true
fi
rm -f "$ROOT/.dbdump.php"
manifest "database/seed.php" "--------" "reproducible seeder (SQL is derived)"
[ -s "$T/database/congruency.dump.sql" ] && manifest "database/congruency.dump.sql" "--------" "deterministic content dump"

# --- 6. docs + install ---------------------------------------------------------------
echo ">> [6/6] docs + install instructions"
for f in LINEAGE.md submission_00.txt README.md; do
  [ -f "$HERE/$f" ] && cp "$HERE/$f" "$T/docs/$f"
done

cat > "$DEST/README.md" <<README
# Tournament package — one serializable object

A single git monorepo that contains an entire code-evolution tournament and is designed
to hold future ones. Serialize the whole thing to one file:

    git bundle create tournament.bundle --all      # (already emitted alongside this repo)

and re-hydrate it anywhere, offline:

    git clone tournament.bundle tournament && cd tournament

## What's inside

    tournaments/congruency-2026/     one tournament (add siblings for future tournaments)
      brief/        the mission
      lineage/      code lineage as a bundle: original -> initial refactors -> submission
      submission/   the evolved entry, checked out for browsing
      apparatus/    harness / tests / bugs / coverage / pwdriver — each a self-contained bundle
      database/     deterministic seed + SQL dump (rebuild the DB, no live binaries shipped)
      docs/         architecture, provenance, layout
      MANIFEST.txt  inventory + the source commit each piece came from

Nested repos are their OWN bundles (full history, self-contained). The database is a
reproducible seed/dump, not a binary. The PHP interpreter is an INSTALL note, not a blob —
see INSTALL.md. Everything needed to rebuild and run is content or instruction.

## Future tournaments

Drop another directory under \`tournaments/\` (e.g. \`tournaments/congruency-2027/\`) with the
same shape and re-bundle. One object, many tournaments, full history preserved.
README

cat > "$DEST/INSTALL.md" <<INSTALL
# Install & run

## 0. Re-hydrate
    git clone tournament.bundle tournament && cd tournament

## 1. Unpack a nested repo (example: the code lineage)
    git clone tournaments/congruency-2026/lineage/tournament-lineage.bundle lineage
    git -C lineage log --oneline           # original -> refactors -> submission
    git -C lineage diff refactors submission

## 2. Prerequisite: a PHP 8 interpreter
The tournament ran on a static PHP 8 build (~7 MB) that is NOT shipped in this package
(binaries don't belong in git history). Any PHP 8.x works. Point tooling at it via:
    export CONGRUENCEY_PHP=/path/to/php

## 3. Rebuild the database (no live DB is shipped)
    cd tournaments/congruency-2026
    \$CONGRUENCEY_PHP database/seed.php          # regenerates congruency.sqlite from scratch
    #   or load the captured content dump into a fresh sqlite file:
    #   sqlite3 congruency.sqlite < database/congruency.dump.sql

## 4. Run the submission's oracle (self-contained, no DB/server/JS)
    cd tournaments/congruency-2026/submission/tests/parser
    \$CONGRUENCEY_PHP run.php                     # exit 0 iff all assertions pass

## 5. Serve the redesigned showcase (server-side, zero JavaScript)
    cd tournaments/congruency-2026/submission
    \$CONGRUENCEY_PHP -S 0.0.0.0:8901 showcase/router.php
    #   open http://localhost:8901/

## 6. Unpack the apparatus repos as needed
    git clone tournaments/congruency-2026/apparatus/harness.bundle  harness
    git clone tournaments/congruency-2026/apparatus/tests.bundle    tests
    git clone tournaments/congruency-2026/apparatus/bugs.bundle     bugs
INSTALL

manifest "docs/, README.md, INSTALL.md" "--------" "documentation + run steps"

# --- seal: commit the monorepo and emit the single-file bundle -----------------------
echo ">> sealing monorepo + emitting tournament.bundle"
git -C "$DEST" init -q
GIT_AUTHOR_DATE='2026-07-04T00:00:00' GIT_COMMITTER_DATE='2026-07-04T00:00:00' \
git -C "$DEST" -c user.name='tournament-apparatus' -c user.email='apparatus@congruency.local' \
  add -A && \
GIT_AUTHOR_DATE='2026-07-04T00:00:00' GIT_COMMITTER_DATE='2026-07-04T00:00:00' \
git -C "$DEST" -c user.name='tournament-apparatus' -c user.email='apparatus@congruency.local' \
  commit -q -m "Tournament package: congruency-2026 (brief + lineage + submission + apparatus + database + docs)"
git -C "$DEST" bundle create "$DEST/tournament.bundle" --all >/dev/null 2>&1

# --- verify --------------------------------------------------------------------------
echo
echo ">> VERIFY — the single object re-hydrates offline:"
git bundle verify "$DEST/tournament.bundle" 2>&1 | grep -iE 'is okay|contains' | sed 's/^/   /'
rm -rf "$ROOT/.verify-tmp"
git clone -q "$DEST/tournament.bundle" "$ROOT/.verify-tmp" 2>/dev/null
git -C "$ROOT/.verify-tmp" fsck --full >/dev/null 2>&1 && echo "   fsck: clean, all objects present"
files=$(git -C "$ROOT/.verify-tmp" ls-files | wc -l)
nested=$(git -C "$ROOT/.verify-tmp" ls-files | grep -c '\.bundle$')
rm -rf "$ROOT/.verify-tmp"
echo "   re-hydrated files: $files  (nested self-contained bundles: $nested)"
echo
echo ">> DONE"
printf "   package dir : %s  (%s)\n" "$DEST" "$(du -sh "$DEST" | cut -f1)"
printf "   ONE FILE    : %s  (%s)\n" "$DEST/tournament.bundle" "$(du -h "$DEST/tournament.bundle" | cut -f1)"
echo
echo "   inventory:"; sed 's/^/     /' "$T/MANIFEST.txt"
