<?php
/*
Copyright (C) 2006 Steven Peterson
Congruency is free software, licensed under the GNU GPLv2 or later.
See the LICENSE file in the project root for full license terms.
*/
if ( !class_exists('Document')){
   class Document implements Tag_Interface{
		private $documentTitle;
		private $template;
		private $content_outline;
		private $documentDescription;
		private $key;
		private $document_tag;

/*Methods of instantiation */	
    	public function __construct(){
    		$this->create_document_tag();
    	}

		public static function sql_assoc_array($array_data){
			$document = NULL;
			if(!empty($array_data)){
				$document = new Document();	
				$document->setTemplate( $array_data[ DocumentDAO::FIELD_NAME_CONTENT ] );
				$document->setTitle( $array_data[ DocumentDAO::FIELD_NAME_TITLE] );
				$document->setDescription( $array_data[ DocumentDAO::FIELD_NAME_DESCRIPTION] );
				$document->setKey($array_data[DocumentDAO::FIELD_NAME_DOCUMENT_ID] );
				$document->set_content_outline($array_data[DocumentDAO::FIELD_NAME_CONTENT_ID] );				
			}
			return $document;
		}
    	
/*Accessors and mutators*/	
		public function getKey(){
			return $this->key;
		}

		public function setKey($arg){
	   	   $this->key = $arg;
		}

		public function getTitle(){
			return $this->documentTitle;
		}

		public	function setTitle($arg){
			$this->documentTitle = $arg;
		}

		public	function setDescription($arg){
			$this->documentDescription = $arg;
		}
	
		public function getDescription(){
			return $this->documentDescription;
		}

		public function getTemplate(){
			return $this->template;
		}

		public function setTemplate($template){
			$this->template = $template;			
		}

		public function set_content_outline($content_id){
			$this->content_outline = $content_id;
		}
		
		public function get_content_outline(){
			return $this->content_outline;	
		}

/* class logic*/
		public function get_document(){
			return $this->template;
		}
		
		/*executes all tags in a document. 
		 * A recursive process, in which
		 * the Tag Invocation Strings are replaced 
		 * by the text generated by the tag objects invoked.*/
		public function __toString(){
			return Tag_Wrapper::execute_all_tags($this->document_tag);		
		}
		
		private function create_document_tag(){
			if(!isset($this->document_tag)){
				$this->document_tag = Tag_Wrapper::create_document_tag($this);
			}	
		}
   }
}
?>